project_id = "hzbwyudnflzlutkeobcu"

[functions.ai-tutor]
verify_jwt = false

[functions.generate-quiz]
verify_jwt = false

[functions.generate-image]
verify_jwt = false

[functions.text-embeddings]
verify_jwt = false
